### ISSUE TITLE
syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'

### ISSUE THREAD

**Issue by mcdoyaji** [scottbedard/oc-debugbar-plugin#7] opened 2016-02-27 13:14 UTC
I Installed this fantastic plugin.

Then I get error page.

![_012](https://cloud.githubusercontent.com/assets/11155414/13373017/09a2d5ba-dd9f-11e5-8de5-4ecff1a1c4f5.png)

OK. 'debug' = false could turn this error page off. 

But I can't access front-page except backend...

**Comment by scottbedard** [comment] 2016-02-27 19:40
Duplicate of https://github.com/scottbedard/oc-debugbar-plugin/issues/6

This is a known problem in the debugbar dependency, it can be solved by upgrading your version of PHP to 5.5 or higher.

**Closed as completed by scottbedard** 2016-02-27 19:40 UTC
